//
//  Copyright © 2017 - 2018 Werner Freytag. All rights reserved.
//

import SwiftToolbox
import XCTest

class StringEncodingsExtensionTests: XCTestCase {
    func testComplete() {
        let _: [String.Encoding] = [
            .macOSRoman,
            .macJapanese,
            .macTraditional,
            .macKorean,
            .macArabic,
            .macHebrew,
            .macGreek,
            .macCyrillic,
            .macDevanagari,
            .macGurmukhi,
            .macGujarati,
            .macThai,
            .macSimplified,
            .macTibetan,
            .macCentral,
            .symbol,
            .macDingbats,
            .macTurkish,
            .macCroatian,
            .macIcelandic,
            .macRomanian,
            .macCeltic,
            .macGaelic,
            .macKeyboard,
            .macFarsi,
            .macUkrainian,
            .macInuit,
            .utf16,
            .UTF7,
            .utf8,
            .utf32,
            .utf16BigEndian,
            .utf16LittleEndian,
            .utf32BigEndian,
            .utf32LittleEndian,
            .isoLatin1,
            .isoLatin2,
            .isoLatin3,
            .isoLatin4,
            .isoLatinCyrillic,
            .isoLatinArabic,
            .isoLatinGreek,
            .isoLatinHebrew,
            .isoLatin5,
            .isoLatin6,
            .isoLatinThai,
            .isoLatin7,
            .isoLatin8,
            .isoLatin9,
            .isoLatin10,
            .dosLatinUS,
            .dosGreek,
            .dosBalticRim,
            .dosLatin1,
            .dosGreek1,
            .dosLatin2,
            .dosCyrillic,
            .dosTurkish,
            .dosPortuguese,
            .dosIcelandic,
            .dosHebrew,
            .dosCanadianFrench,
            .dosArabic,
            .dosNordic,
            .dosRussian,
            .dosGreek2,
            .dosThai,
            .shiftJIS,
            .dosChineseSimplif,
            .dosKorean,
            .dosChineseTrad,
            .windowsCP1252,
            .windowsCP1250,
            .windowsCP1251,
            .windowsCP1253,
            .windowsCP1254,
            .windowsHebrew,
            .windowsArabic,
            .windowsBalticRim,
            .windowsVietnamese,
            .ascii,
            .shiftJIS_X0213,
            .GBK_95,
            .GB_18030_2000,
            .iso2022JP,
            .ISO_2022_JP_2,
            .ISO_2022_JP_1,
            .ISO_2022_CN,
            .ISO_2022_KR,
            .japaneseEUC,
            .EUC_CN,
            .EUC_TW,
            .EUC_KR,
            .shiftJIS_plain,
            .KOI8_R,
            .big5,
            .macRomanLatin1,
            .HZ_GB_2312,
            .big5_HKSCS_1999,
            .KOI8_U,
            .big5_E,
            .nextstep,
            .nonLossyASCII,
            .EBCDIC_US,
            .EBCDIC_CP037,
        ]

        // Result may differ between devices / OSses, so we only have this check to validate
        // the code runs
        XCTAssert(!String.availableStringEncodings.isEmpty)
    }

    static var allTests = [
        ("testComplete", testComplete),
    ]
}
